[".local/share/powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/refs/tags/v1.16.1.tar.gz"
    exact = true
    stripComponents = 1
[".local/share/fast-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zdharma-continuum/fast-syntax-highlighting/archive/refs/tags/v1.55.tar.gz"
    exact = true
    stripComponents = 1
