#!/usr/bin/bash

if [ "$(uname)" = "Darwin" ]; then
    alias ls='gls --color=auto --group-directories-first'
    alias sed='gsed'
elif [ "$(uname)" = "Linux" ]; then
    alias ls='ls --color=auto --group-directories-first'
fi

alias la='ls -A'
alias ll='ls -Alh'
