#!/usr/bin/bash

# macOS gnu coreutils aliases
if command -v gsed &> /dev/null; then
    alias sed='gsed'
fi

if command -v gls &> /dev/null; then
    alias ls='gls --color=auto --group-directories-first'
else
    alias ls='ls --color=auto --group-directories-first'
fi

alias la='ls -A'
alias ll='ls -Alh'
