#!/usr/bin/bash

if [[ "$PATH" != *"$HOME/.local/bin"* ]]; then
    export PATH="$HOME/.local/bin:$PATH"
fi

if [ -d "/opt/homebrew" ]; then
    export HOMEBREW_PREFIX="/opt/homebrew"
    export HOMEBREW_CELLAR="/opt/homebrew/Cellar"
    export HOMEBREW_REPOSITORY="/opt/homebrew"
    export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}"
    export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:"
    export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}"
fi

if command -v go &> /dev/null; then
    GOPATH="$(go env GOPATH)"
    export GOPATH
    export PATH="$GOPATH/bin:$PATH"
fi

for file in /etc/bashrc /opt/homebrew/etc/profile.d/bash_completion.sh; do
    if [ -f "$file" ]; then
        source "$file"
    fi
done

if [ -f ~/.bash_aliases ]; then
    source ~/.bash_aliases
fi

shopt -s checkwinsize
shopt -s direxpand
shopt -s dirspell
shopt -s histappend

HISTSIZE=1000

export EDITOR=nvim
export VISUAL=nvim

# DarkSlateGray3
user_color=$'\[\e[38;5;116m\]'
# SkyBlue2
host_color=$'\[\e[38;5;111m\]'
# NavajoWhite1
cwd_color=$'\[\e[38;5;223m\]'
clear_color=$'\[\e[0m\]'

PS1="${user_color}\u${clear_color}@${host_color}\h${clear_color}:${cwd_color}\W${clear_color}"

if [ -f "${HOME}/.local/bin/git-prompt.sh" ]; then
    export GIT_PS1_SHOWCOLORHINTS=1
    export GIT_PS1_SHOWDIRTYSTATE=1
    source "${HOME}/.local/bin/git-prompt.sh"
    export PS1="${PS1}\$(__git_ps1 \" (%s)\")$ "
else
    export PS1="${PS1}$ "
fi

export PS2="${user_color}> ${clear_color}"

unset rc
