#!/usr/bin/bash

if [[ "$PATH" != *"$HOME/.local/bin"* ]]; then
    export PATH="$HOME/.local/bin:$PATH"
fi

if [ -d "/opt/homebrew" ]; then
    export HOMEBREW_PREFIX="/opt/homebrew"
    export HOMEBREW_CELLAR="/opt/homebrew/Cellar"
    export HOMEBREW_REPOSITORY="/opt/homebrew"
    export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}"
    export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:"
    export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}"
fi

if command -v go &> /dev/null; then
    GOPATH="$(go env GOPATH)"
    export GOPATH
    export PATH="$GOPATH/bin:$PATH"
fi

for file in /etc/bashrc /opt/homebrew/etc/profile.d/bash_completion.sh; do
    if [ -f "$file" ]; then
        source "$file"
    fi
done

if [ -f ~/.bash_aliases ]; then
    source ~/.bash_aliases
fi

shopt -s checkwinsize
shopt -s direxpand
shopt -s dirspell
shopt -s histappend

HISTSIZE=1000

export EDITOR=nvim
export VISUAL=nvim

# DarkSlateGray3
user_color=$'\001\e[38;5;116m\002'
# SkyBlue2
host_color=$'\001\e[38;5;111m\002'
# NavajoWhite1
cwd_color=$'\001\e[38;5;223m\002'
# LightCoral
err_color=$'\001\e[38;5;210m\002'
clear_color=$'\001\e[0m\002'

# this is useful for identifying misbehaved applications
ret_prompt() {
    ret="$?"
    if [ "$ret" -ne 0 ]; then
        printf "%s %s %s" "${err_color}" "$ret" "${clear_color}"
    fi
}

PROMPT_COMMAND='printf "\033]0;%s\007" "${PWD/#$HOME/\~}"'

PS1="${user_color}\u${clear_color}@${host_color}\h${clear_color}:${cwd_color}\W${clear_color}\$(ret_prompt)\$ "

if [ -f "${HOME}/.local/bin/git-prompt.sh" ]; then
    export GIT_PS1_SHOWCOLORHINTS=1
    export GIT_PS1_SHOWDIRTYSTATE=1
    source "${HOME}/.local/bin/git-prompt.sh"
    PS1="\$(__git_ps1 '[%s]')${PS1}"
fi

export "PS1"
export PS2="${user_color}>${clear_color} "

unset rc
