-- Plugins and settings are in their own modules
require("options")
require("keymaps")
require("autocmds")
require("mini-deps-conf")
require("catppuccin-conf")
-- require("nvim-cmp-conf")
require("mini-completion-conf")
require("lsp-conf")
require("toggleterm-conf")
require("lualine-conf")
require("fzf-lua-conf")
require("formatter-conf")
require("indent-blankline-conf")
require("neo-tree-conf")
require("nvim-autopairs-conf")
require("nvim-lint-conf")
require("nvim-surround-conf")
require("vim-fugitive-conf")
require("vim-illuminate-conf")
