-- Plugins and settings are in their own modules
require("options")
require("keymaps")
require("autocmds")
require("mini_deps_conf")
require("catppuccin_conf")
-- require("nvim_cmp_conf")
require("mini_completion_conf")
require("lsp_conf")
require("toggleterm_conf")
require("lualine_conf")
require("fzf_lua_conf")
require("formatter_conf")
require("indent_blankline_conf")
require("neo_tree_conf")
require("nvim_autopairs_conf")
require("nvim_lint_conf")
require("nvim_surround_conf")
require("vim_fugitive_conf")
require("vim_illuminate_conf")

-- neovim lua debugging, hopefully we do not need this again
-- require("nvim-dap-conf")
-- require("osv-conf")
